version: "3.9"
services:
  midb:
    image: mateofuentes/bd_block:v1
    ports:
      - "1433:1433"
  miback:
    image: mateofuentes/app_back:v1
    ports:
      - "5000:5000"
    links:
      - midb
  mifront:
    image: miguelhernandezdev/mifront:v1
    ports:
      - "4200:4200"
    links:
      - miback
